language: node_js
node_js:
- 5.9.1
deploy:
  api_key:
    secure: Shjy758P19ZG5EUGyzRD3tpk4OMnDSvS+iXFwMJ+sSyAeVXWRKU21tK23l552DOTxOH+5GGmuToNuoAjqFEzs9CKVL2Fjj/QI0B7+q58fTbIutsz2gN8vZackkgF1Cv27sQ6NciQ5Ms6B0A3QnEFoU/ppPt7a+XsHLmF+qlm31MSkui5q1m9zr1bBnI2n5bcS0gMs48O+E45px53bmWIJNXQxefHuJs/zVBIsyfBOHU1JwxQ4Hy/9A1ys8M9kj5cKU8c5tMY22DsbmHQ/zqZtYiSXvvecn+Oaze8eiUhFkHF0INWl16V6mQxJvJzsZCgI4bIQcP49UdeXUcSV7xwCQlmJ07Z6/m9gyNBr9L7uilhwFyHVpNDeqP32wEgW/1NQiGQAX8NtdBmYgYV3OzrrJ3Z6Q1kgu4bA82V/6mLzstYxk+rjfoQBZ5TiHxc/SE3+Qu3NDbov/j0bY/s4FwnzcaSU6aI1XM0a/n8qtDzTBjH18ImRF4kkZRMLET3ZkLvuX2dJP2G0Wk5Pwj2RNmvk3AxaETxGYUDu7VL4IKxdC/XYBuj7bRvNdGAtsG/tZ2csqlBBbmHqGPtc02n6e3PaUnMPeJ4BW3arfbbjTNB8bYfpuA5Iur/UA7oxntfajoKOQlxlM9nEy7iNe2fCGsNOwR7Ocbz0dFcZPvh97ZG5l4=
